[init ]

diff --git a/tests/data/Makefile.am b/tests/data/Makefile.am
--- a/tests/data/Makefile.am
+++ b/tests/data/Makefile.am
@@ -1,13 +1,47 @@
-all:
+#***************************************************************************
+#                                  _   _ ____  _
+#  Project                     ___| | | |  _ \| |
+#                             / __| | | | |_) | |
+#                            | (__| |_| |  _ <| |___
+#                             \___|\___/|_| \_\_____|
+#
+# Copyright (C) 1998 - 2021, Daniel Stenberg, <daniel@haxx.se>, et al.
+#
+# This software is licensed as described in the file COPYING, which
+# you should have received as part of this distribution. The terms
+# are also available at https://curl.se/docs/copyright.html.
+#
+# You may opt to use, copy, modify, merge, publish, distribute and/or sell
+# copies of the Software, and permit persons to whom the Software is
+# furnished to do so, under the terms of the COPYING file.
+#
+# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
+# KIND, either express or implied.
+#
+###########################################################################
+iall:
 install:
-
 test:
-	[ -f test1 ] || ln -s $(srcdir)/test* .
 
-EXTRA_DIST = \
-test1    test104  test13   test19   test21   test3    test5    \
-test10   test105  test14   test2    test22   test300  test6    \
-test100  test106  test15   test20   test23   test33   test7    \
-test101  test107  test16   test200  test24   test4    test8    \
-test102  test11   test17   test201  test25   test400  test9    \
-test103  test12   test18   test202  test26   test43   
+# TESTCASES are taken from Makefile.inc
+include Makefile.inc
+
+EXTRA_DIST = $(TESTCASES) DISABLED CMakeLists.txt
+
+filecheck:
+	@mkdir test-place; \
+	cp "$(top_srcdir)"/tests/data/test[0-9]* test-place/; \
+	rm -f test-place/*~; \
+	for f in $(EXTRA_DIST); do \
+	  if test -f "$(top_srcdir)/tests/data/$$f"; then \
+	    rm -f "test-place/$$f"; \
+	  else \
+	    echo "$$f is listed but missing!"; \
+	  fi \
+	done; \
+	echo "Local files not present in EXTRA_DIST:" ; \
+	ls test-place; \
+	! ls test-place | grep . >/dev/null ; \
+	RC=$$? ; \
+	rm -rf test-place ; \
+	exit $$RC
